### ISSUE TITLE
RuntimeError: copy_if failed to synchronize: an illegal memory access was encountered

### ISSUE THREAD

**Issue by mengjiexu** [facebookresearch/maskrcnn-benchmark#229]
one month ago, I run my code was success.

my environment:
ubuntu 18.04
cuda 9.0
cudnn 7.4.1
torch-nightly

now I setup the maskrcnn_benchmark again and run the code, It shows the error below:

    results = model.predict_one_img(image)
  File "/home/xmj/mycipan/workfolder/maskrcnn-benchmark/demo/predictor.py", line 161, in predict_one_img
    predictions = self.compute_prediction(image)
  File "/home/xmj/mycipan/workfolder/maskrcnn-benchmark/demo/predictor.py", line 212, in compute_prediction
    predictions = self.model(image_list)
  File "/home/xmj/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/module.py", line 479, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xmj/mycipan/workfolder/maskrcnn-benchmark/maskrcnn_benchmark/modeling/detector/generalized_rcnn.py", line 50, in forward
    proposals, proposal_losses = self.rpn(images, features, targets)
  File "/home/xmj/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/module.py", line 479, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xmj/mycipan/workfolder/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/rpn.py", line 96, in forward
    return self._forward_test(anchors, objectness, rpn_box_regression)
  File "/home/xmj/mycipan/workfolder/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/rpn.py", line 122, in _forward_test
    boxes = self.box_selector_test(anchors, objectness, rpn_box_regression)
  File "/home/xmj/anaconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/modules/module.py", line 479, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xmj/mycipan/workfolder/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/inference.py", line 138, in forward
    sampled_boxes.append(self.forward_for_single_feature_map(a, o, b))
  File "/home/xmj/mycipan/workfolder/maskrcnn-benchmark/maskrcnn_benchmark/modeling/rpn/inference.py", line 113, in forward_for_single_feature_map
    boxlist = remove_small_boxes(boxlist, self.min_size)
  File "/home/xmj/mycipan/workfolder/maskrcnn-benchmark/maskrcnn_benchmark/structures/boxlist_ops.py", line 46, in remove_small_boxes
    (ws >= min_size) & (hs >= min_size)
RuntimeError: copy_if failed to synchronize: an illegal memory access was encountered

**Comment by fmassa** [comment]
Hi,

I believe this was a regression in PyTorch that was fixed yesterday.
Could you try with the latest pytorch nightly, or if it doesnt solve it maybe wait until tomorrow and try again to be sure that the fix got in?

**Comment by mengjiexu** [comment]
Thank you, I will try

**Comment by shayxurui** [comment]
do you solve this problem? i meet same problem when i training the net

**Comment by XdpAreKid** [comment]
@shayxurui Did you fix that??? i meet same problem at box_head/loss.py when training

**Comment by fmassa** [comment]
@XdpAreKid update your pytorch installation and recompile `maskrcnn-benchmark` (after removing the `build` folder) and the error should disappear.

**Comment by zimenglan-sysu-512** [comment]
hi @XdpAreKid 
did u fixed this problem? it happened after several thousand iterations training. i use pytorch 1.0 instead of pytorch nightly.

btw, @fmassa 
why [select_over_all_levels](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/modeling/rpn/inference.py#L157) is not consistent in train and test phase?

**Comment by XdpAreKid** [comment]
I fixed that, I also used pytorch 1.0 stable.Do u  recompile
maskrcnn-benchmark (after removing the build folder) ?

zimenglan <notifications@github.com> 于2018年12月21日周五 上午10:41写道：

**Comment by zimenglan-sysu-512** [comment]
right, i rebuild maskrcnn-benchmark after removing the build folder. it's sometimes happening after several thousand iterations.

**Comment by fmassa** [comment]
@zimenglan-sysu-512 the fact that you still experience those errors are weird, I don't know what it could be.

About the `select_over_all_levels`, this is a legacy behavior (read BUG) from Detectron, and I kept it as is for consistency with the previous implementation.

**Comment by fm-soldel** [comment]
True
