### ISSUE TITLE
could not convert ‘Double’ from ‘c10::ScalarType’ to ‘<type error>’ AT_PRIVATE_CASE_TYPE(at::ScalarType::Double, double, __VA_ARGS__) 

### ISSUE THREAD

**Issue by srasool** [facebookresearch/maskrcnn-benchmark#556]
Getting few errors while building latest from source;

=======================================
site-packages/torch/include/ATen/Dispatch.h:15:17:`` error: switch quantity not an integer switch (TYPE) { \ ^ /maskrcnn_benchmark/csrc/cpu/ROIAlign_cpu.cpp:242:3: note: in expansion of macro ‘AT_DISPATCH_FLOATING_TYPES’ AT_DISPATCH_FLOATING_TYPES(input.type(), "ROIAlign_forward", [&] { ^~~~~~~~~~~~~~~~~~~~~~~~~~ /python3.7/site-packages/torch/include/ATen/Dispatch.h:16:44: error: could not convert ‘Double’ from ‘c10::ScalarType’ to ‘<type error>’ AT_PRIVATE_CASE_TYPE(at::ScalarType::Double, double, __VA_ARGS__) \ ^ /python3.7/site-packages/torch/include/ATen/Dispatch.h:8:8: note: in definition of macro ‘AT_PRIVATE_CASE_TYPE’ case enum_type: { \ ^~~~~~~~~ /maskrcnn_benchmark/csrc/cpu/ROIAlign_cpu.cpp:242:3: note: in expansion of macro ‘AT_DISPATCH_FLOATING_TYPES’ AT_DISPATCH_FLOATING_TYPES(input.type(), "ROIAlign_forward", [&] { ^~~~~~~~~~~~~~~~~~~~~~~~~~ /python3.7/site-packages/torch/include/ATen/Dispatch.h:17:44: error: could not convert ‘Float’ from ‘c10::ScalarType’ to ‘<type error>’ AT_PRIVATE_CASE_TYPE(at::ScalarType::Float, float, __VA_ARGS__) \ ^ /python3.7/site-packages/torch/include/ATen/Dispatch.h:8:8: note: in definition of macro ‘AT_PRIVATE_CASE_TYPE’ case enum_type: { \ ^~~~~~~~~ /maskrcnn_benchmark/csrc/cpu/ROIAlign_cpu.cpp:242:3: note: in expansion of macro ‘AT_DISPATCH_FLOATING_TYPES’ AT_DISPATCH_FLOATING_TYPES(input.type(), "ROIAlign_forward", [&] { ^~~~~~~~~~~~~~~~~~~~~~~~~~ /python3.7/site-packages/torch/include/c10/core/Device.h:5:0, from /python3.7/site-packages/torch/include/c10/core/Allocator.h:6, from/python3.7/site-packages/torch/include/ATen/ATen.h:3, from /python3.7/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3, from python3.7/site-packages/torch/include/torch/script.h:3, from /maskrcnn_benchmark/csrc/cpu/vision.h:3, from /maskrcnn_benchmark/csrc/cpu/ROIAlign_cpu.cpp:2: /python3.7/site-packages/torch/include/ATen/Dispatch.h:19:51: error: ‘toString’ was not declared in this scope AT_ERROR(#NAME, " not implemented for '", toString(TYPE), "'"); \ ^ /python3.7/site-packages/torch/include/c10/util/Exception.h:134:88: note: in definition of macro ‘AT_ERROR’ throw ::c10::Error({__func__, __FILE__, static_cast<uint32_t>(__LINE__)}, ::c10::str(__VA_ARGS__)) ^~~~~~~~~~~ /maskrcnn_benchmark/csrc/cpu/ROIAlign_cpu.cpp:242:3: note: in expansion of macro ‘AT_DISPATCH_FLOATING_TYPES’ AT_DISPATCH_FLOATING_TYPES(input.type(), "ROIAlign_forward", [&] { ^~~~~~~~~~~~~~~~~~~~~~~~~~ /python3.7/site-packages/torch/include/ATen/Dispatch.h:19:51: note: suggested alternatives: AT_ERROR(#NAME, " not implemented for '", toString(TYPE), "'"); \ ^ /python3.7/site-packages/torch/include/c10/util/Exception.h:134:88: note: in definition of macro ‘AT_ERROR’ throw ::c10::Error({__func__, __FILE__, static_cast<uint32_t>(__LINE__)}, ::c10::str(__VA_ARGS__)) ^~~~~~~~~~~ /maskrcnn_benchmark/csrc/cpu/ROIAlign_cpu.cpp:242:3: note: in expansion of macro ‘AT_DISPATCH_FLOATING_TYPES’ AT_DISPATCH_FLOATING_TYPES(input.type(), "ROIAlign_forward", [&] { ^~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by fmassa** [comment]
I think this should be fixed via https://github.com/facebookresearch/maskrcnn-benchmark/pull/555

**Comment by fmassa** [comment]
Let me know if this isn't the case

**Comment by sniklaus** [comment]
This might still not be resolved, it just throws a different error now.

```
nms_cpu.cpp:71:46: error: invalid initialization of reference of type ‘const at::Type&’ from expression of type ‘c10::ScalarType’
```

Thank you for looking into this Francisco!

**Comment by sniklaus** [comment]
I see what's going on, I have not been using PyTorch nightly but `1.0.1` instead. Using the following commit seems to work even without nightly: `git checkout 90080e60cc4a9252d019f475af044c9d4119b09b`

**Comment by fmassa** [comment]
Yes, now we need to use PyTorch master if we use last maskrcnn-benchmark

**Comment by LUCKMOONLIGHT** [comment]
> I see what's going on, I have not been using PyTorch nightly but `1.0.1` instead. Using the following commit seems to work even without nightly: `git checkout 90080e60cc4a9252d019f475af044c9d4119b09b`

Thanks for you advices,the error of `python setup.py build develop` has fixed!

**Comment by maomaochongchh** [comment]
@LUCKMOONLIGHT Hello, how to use that "git checkout 90080e60cc4a9252d019f475af044c9d4119b09b", I got that error even with PyTorch 1.0 nightly.

**Comment by LUCKMOONLIGHT** [comment]
my pytorch version is 1.0  not nightly




| |
LuckMoon
|
|
邮箱：13249433115@163.com
|

Signature is customized by Netease Mail Master

On 03/17/2019 15:45, Crystal wrote:

@LUCKMOONLIGHT Hello, how to use that "git checkout 90080e6", I got that error even with PyTorch 1.0 nightly.

**Comment by maomaochongchh** [comment]
@LUCKMOONLIGHT Thanks for your reply. I have not used git before, so I studied it just now. Which path should I run "git checkout ...." in?

**Comment by LUCKMOONLIGHT** [comment]
you are right,just directe input “git checkout.....




| |
LuckMoon
|
|
邮箱：13249433115@163.com
|

Signature is customized by Netease Mail Master

On 03/17/2019 17:15, Crystal wrote:

@LUCKMOONLIGHT Thanks for your reply. I have not used git before, so I studied it just now. Which path should I run "git checkout ...." in?
