### ISSUE TITLE
0% utilization in second GPU in 2x GPUs training

### ISSUE THREAD

**Issue by yxchng** [facebookresearch/maskrcnn-benchmark#659]
## 🐛 Bug

0% utilization in second GPU in 2x GPUs training

![Screenshot from 2019-04-10 17-25-07](https://user-images.githubusercontent.com/10518587/55867787-bf684280-5bb5-11e9-8d48-658b46e58382.png)

Is the second GPUs only used to store tensors? Is the multi GPUs training in this codebase specially implemented, such that it is different from the multi GPUs training in PyTorch?

## To Reproduce

Run training code with 2 GPUs

## Expected behavior

Comparable utilization in 2 GPUs?

## Environment

> PyTorch version: 1.0.0.dev20190409
> Is debug build: No
> CUDA used to build PyTorch: 10.0.130
> 
> OS: Ubuntu 16.04.4 LTS
> GCC version: (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010
> CMake version: version 3.5.1
> 
> Python version: 3.5
> Is CUDA available: Yes
> CUDA runtime version: 10.0.130
> GPU models and configuration: 
> GPU 0: GeForce RTX 2080 Ti
> GPU 1: TITAN X (Pascal)
> 
> Nvidia driver version: 418.39
> cuDNN version: Could not collect
> 
> Versions of relevant libraries:
> [pip] Could not collect
> [conda] Could not collect
>         Pillow (6.0.0)
>

**Comment by fmassa** [comment]
How did you launch your 2 GPU job? This behavior is not expected.

**Comment by fmassa** [comment]
Also, I just noticed that you have two different GPUs. What might be happening is that the fastest GPU is waiting for the slowest GPU to finish its iteration.

It seems that 2080Ti do not have peer2peer enabled, which can make multi-GPU training much slower as memory transfer between GPUs should pass via the CPU

https://www.pugetsystems.com/labs/hpc/P2P-peer-to-peer-on-NVIDIA-RTX-2080Ti-vs-GTX-1080Ti-GPUs-1331/

**Comment by yxchng** [comment]
I reinstalled NVIDIA driver and installed the latest pytorch-nightly and the problem disappears.

**Comment by yxchng** [comment]
It seems like the program turns into zombie process sometimes, meaning it is no longer running but still hogging the memory. I thought I have solved it but apparently not. 

It happens often when I ctrl-c or when something interrupts it (like when downloading model but connection is down).

**Comment by fmassa** [comment]
This is a problem with the cleanup in PyTorch distributed launch utility, when one of the process dies the others might not be killed.

ccing @pietern to know if he has ideas on how to avoid this situation.

**Comment by chengyangfu** [comment]
If you use `ctrl-c` to stop the program, be careful to kill every process carefully. In your case(2gpus), there are around 2 + 8(dataloading) processes. I usually will run `ps aux | grep python` to kill everything related to the training program.

**Comment by yxchng** [comment]
@chengyangfu My expectation is that the `ctrl-c` signal should propagate to every process and I shouldn't have to manually kill all of them. A good implementation of multiprocessing code should not have such problem and so I would think that this is a bug.

I was browsing through the issues and seems like this issue https://github.com/facebookresearch/maskrcnn-benchmark/issues/58 is related to the problem discussed here. Their root problem is probably the same where the coordination between different processes is problematic.

**Comment by VCBE123** [comment]
I meet the same problem

**Comment by sanshibayuan** [comment]
Same here

**Comment by Marcovaldong** [comment]
I met a similar problem. I trained the model with 4 gpus. Training for thousand mini-batches, one process dead (I cannot get when and how it dead) and the utilization of the other three gpus are maintained at 100%, but the training has been stopped. 
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 387.26                 Driver Version: 387.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:04:00.0 Off |                  N/A |
| 20%   27C    P8    16W / 250W |      0MiB / 11172MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:05:00.0 Off |                  N/A |
| 20%   32C    P8    16W / 250W |      0MiB / 11172MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  Off  | 00000000:08:00.0 Off |                  N/A |
| 20%   28C    P8    16W / 250W |      0MiB / 11172MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 108...  Off  | 00000000:09:00.0 Off |                  N/A |
| 20%   30C    P8    16W / 250W |      0MiB / 11172MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  GeForce GTX 108...  Off  | 00000000:85:00.0 Off |                  N/A |
| 24%   58C    P2    77W / 250W |   3764MiB / 11172MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   5  GeForce GTX 108...  Off  | 00000000:86:00.0 Off |                  N/A |
| 20%   54C    P2    78W / 250W |   4110MiB / 11172MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   6  GeForce GTX 108...  Off  | 00000000:89:00.0 Off |                  N/A |
| 20%   29C    P8    15W / 250W |     41MiB / 11172MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  GeForce GTX 108...  Off  | 00000000:8A:00.0 Off |                  N/A |
| 24%   58C    P2    74W / 250W |   3906MiB / 11172MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    4     65245      C   ...ongsq/environments/anaconda3/bin/python  3731MiB |
|    5     65246      C   ...ongsq/environments/anaconda3/bin/python  4077MiB |
|    7     65248      C   ...ongsq/environments/anaconda3/bin/python  3873MiB |
+-----------------------------------------------------------------------------+
```

As shown above, the process which pid should be 65247 has been killed for some reason, How should I fix this problem? I cannot reinstall nvidia driver because of no root right.

**Comment by pietern** [comment]
@Marcovaldong This is not related to the zombie process problem tracked in this issue.

What you're seeing is that a single process crashing causes the remaining processes to launch NCCL kernels that will never complete. This is a known problem with NCCL and has been addressed in the most recent minor release (2.4). There is work in progress to add the error detection to the NCCL bindings in PyTorch in pytorch/pytorch#22907. Once that is done and merged, the remaining processes will raise an error once one of its peers is no longer reachable or has crashed.

**Comment by Marcovaldong** [comment]
@pietern Thanks for your reply. I have fixed my problem. There is a dirty sample in my 700k train dataset, I have checked out it.

**Comment by jrsykes** [comment]
I'm still having this issue in 2022. It occurs when my training process goes awry and a tensor of NaN values is fed to torch.nn.functional.binary_cross_entropy. I then have to close the terminal window and cannot kill the resulting zombie process. The only solution seems to be to restart the server. 
It may be a coincidence but this behaviour is new since upgrading the NVIDIA driver a few days ago.

p.s. training with two different GPUs using nn.DataParallel.

Has anyone found a solution yet? None of the solutions above work for me.

CUDA version: 11.7
PyTorch: 1.11.0
Python 3.7.13
Ubuntu 18.04.6 LTS
NVIDIA-SMI 515.43.04    
Driver Version: 515.43.04

**Comment by ilml** [comment]
Same here
