### ISSUE TITLE
Error after fresh install: Cannot import '_download_url_to_file' from 'torch.utils.model_zoo'

### ISSUE THREAD

**Issue by Jinksi** [facebookresearch/maskrcnn-benchmark#674]
## To Reproduce

1. Install as per instructions (Ubuntu DSVM)
1. Attempt to start training

## Error

The error is:
`ImportError: cannot import name '_download_url_to_file' from 'torch.utils.model_zoo'`

## Additional context
If I am seeing things clearly, `torch.utils.model_zoo` no longer contains `_download_url_to_file`.

**Comment by Jinksi** [comment]
PR already in:
https://github.com/facebookresearch/maskrcnn-benchmark/pull/673

**Comment by my-hello-world** [comment]
how fix it? please

**Comment by Jinksi** [comment]
@my-hello-world as a temp fix, you make [these changes](https://github.com/facebookresearch/maskrcnn-benchmark/pull/673/files#diff-1252846857806d2e6071bf2681a76631) to `maskrcnn_benchmark/utils/model_zoo.py`

**Comment by my-hello-world** [comment]
thx! i got it 😃

**Comment by my-hello-world** [comment]
thx! i got it 😃@JinKsi

**Comment by fmassa** [comment]
Fixed via https://github.com/facebookresearch/maskrcnn-benchmark/pull/698

**Comment by metusnp** [comment]
Hello, 
I am still getting the error in docker image. I update file as proposed temporary fix above but same error shows up. It seems somewhat cached code is run. How can i force it to use normal code instead of **cached**  (well, if that is the case)
thanks in advance
 

Error lines in docker container:
root@a213ed43e084:/home/retinamask/maskrcnn-benchmark/demo# python3 
Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 19:16:44) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from predictor import COCODemo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/retinamask/maskrcnn-benchmark/demo/predictor.py", line 7, in <module>
    from maskrcnn_benchmark.utils.checkpoint import DetectronCheckpointer
  File "/maskrcnn-benchmark/maskrcnn_benchmark/utils/checkpoint.py", line 10, in <module>
    from maskrcnn_benchmark.utils.model_zoo import cache_url
  File "/maskrcnn-benchmark/maskrcnn_benchmark/utils/model_zoo.py", line 5, in <module>
    from torch.utils.model_zoo import _download_url_to_file
ImportError: cannot import name '_download_url_to_file'

And the head content of model_zoo.py is as follows ( I commented out torch.utils related lines):
 root@a213ed43e084:/home/retinamask/maskrcnn-benchmark/demo# head -n 20 ../maskrcnn_benchmark/utils/model_zoo.py 
# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved.
import os
import sys

try:
    from torch.hub import _download_url_to_file
    from torch.hub import urlparse
    from torch.hub import HASH_REGEX

    
   # from torch.utils.model_zoo import _download_url_to_file
  #  from torch.utils.model_zoo import urlparse
  #  from torch.utils.model_zoo import HASH_REGEX
except:
    from torch.hub import _download_url_to_file
    from torch.hub import urlparse
    from torch.hub import HASH_REGEX

from maskrcnn_benchmark.utils.comm import is_main_process
from maskrcnn_benchmark.utils.comm import synchronize

**Comment by smrfeld** [comment]
This came up again, I am on version `1.13.0.dev20220905` - now `_download_url_to_file` is `download_url_to_file` and the correct import path is `torch.hub`, i.e. `from torch.hub import download_url_to_file`.
