### ISSUE TITLE
ModuleNotFoundError: No module named 'maskrcnn_benchmark'

### ISSUE THREAD

**Issue by VellalaVineethKumar** [facebookresearch/maskrcnn-benchmark#742]
## 🐛 Bug

(maskrcnn_benchmark) python@cse-w1:~/maskrcnn-benchmark$ python
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
1.1.0.dev20190501
>>> 
cuda ver: 10.1

i have exactly followed the installation file but then i still get 
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-63734ee6f49e> in <module>
----> 1 from maskrcnn_benchmark.config import cfg
      2 from predictor import COCODemo

ModuleNotFoundError: No module named 'maskrcnn_benchmark'

while running the demo

**Comment by knaggita** [comment]
Hello Vellala, try to add __init__.py in the maskrcnn_benchmark' folder and try again

**Comment by VellalaVineethKumar** [comment]
@knaggita 
Yes, i am following option1, I even tried option2 i still get the same error
i have added __init__.py file in the  maskrcnn_benchmark folder, yet i get the same error.
do i need to redo the steps in install.md file?

**Comment by salliewalecka** [comment]
Hi @VellalaVineethKumar Did you every find the fix to this? I am running into the same thing.

**Comment by Susie2060** [comment]
I think this is because you are not under the correct folder and you need to : cd maskrcnn-benchmark.

**Comment by satyamr1** [comment]
I am in demo folder as instructed in README.md. Also, I am using python 3.6.8 but still I'm getting the reason. What mistake can I be making!

**Comment by salliewalecka** [comment]
I was in the right directory and I never was able to get this working. I was able to get the dockerized demo working but had to make some changes. I have an open PR for the changes if you just want to checkout that version and run. My team just ended up using the new release of torch vision at the end of the day. Hope that helps.

**Comment by satyamr1** [comment]
Thanks for the reply. I want to get this thing working in any way possible. But I don't have any idea of open PR. What it actually is!

**Comment by nancymao** [comment]
Does your computer have a camera? Does it cause the problem?

**Comment by satyamr1** [comment]
Yes i had  the camera but the issue has been resolved now. Actually, torch was automatically getting installed on installing torchvisionorch and hence torch was creating problems (as it was conflicting with torch-nightly. It worked fine after i uninstalled torch using pip.

**Comment by vipermu** [comment]
Hey! I run into the same problem, just adding the `maskrcnn_benchmark` path to `sys.path` it worked for me. You need to first import `sys` and then to append to the path list the path to `maskrcnn_benchmark`, in my case: `sys.path.append("/home/victor/Documents/maskrcnn-benchmark")`.

I also got a problem `maskrcnn_benchmark/layers/nms.py` when importing _C, I solved it by changing line 3 by `from maskrcnn_benchmark.config.defaults import _C`. 

Hope it helps :)

**Comment by WWaynee** [comment]
> Hey! I run into the same problem, just adding the `maskrcnn_benchmark` path to `sys.path` it worked for me. You need to first import `sys` and then to append to the path list the path to `maskrcnn_benchmark`, in my case: `sys.path.append("/home/victor/Documents/maskrcnn-benchmark")`.
> 
> Hope it helps :)

Thanks a lot that my problem has been solved. And I have one more point emphasize: Don't use like this: sys.path.append("~/xxx"). It should be absolute path otherwise the same problem occurs.

**Comment by pranay-ar** [comment]
> > Hey! I run into the same problem, just adding the `maskrcnn_benchmark` path to `sys.path` it worked for me. You need to first import `sys` and then to append to the path list the path to `maskrcnn_benchmark`, in my case: `sys.path.append("/home/victor/Documents/maskrcnn-benchmark")`.
> > Hope it helps :)
> 
> Thanks a lot that my problem has been solved. And I have one more point emphasize: Don't use like this: sys.path.append("~/xxx"). It should be absolute path otherwise the same problem occurs.

I tried doing the same, but it still shows the same error. Any idea why that might be happening? @vipermu

**Comment by mkaur013** [comment]
> Hey! I run into the same problem, just adding the `maskrcnn_benchmark` path to `sys.path` it worked for me. You need to first import `sys` and then to append to the path list the path to `maskrcnn_benchmark`, in my case: `sys.path.append("/home/victor/Documents/maskrcnn-benchmark")`.
> 
> Hope it helps :)

I tried doing the same, but it still shows the same error. 
ModuleNotFoundError: No module named 'maskrcnn_benchmark'

Any solution please

**Comment by WWaynee** [comment]
收到了惹。
